### ISSUE TITLE
Size of iFrame often not resized fully to 100%

### ISSUE THREAD

**Issue by VOOM108** [center-for-learning-management/moodle-filter_h5p#9] opened 2022-02-24 12:24 UTC
Moodle 3.9 - embedding H5P interactive videos - both core h5p and h5p plugin: 

Often, but not always, the content will not be resized to 100% width and the calculated height. This does not happen when showing the h5p-activity directly. Usually the iFrame will first be shown at around 50% width and 300-400px or so height very briefly and then be stretched out fully. 

About 20% of the time it will stick at that small preliminary size, though. Reloading the page or starting to play the video (scrolling down inside the iFrame and finding the play button) will then stretch out the content. 

Still it irritates students and appears "buggy". Any ideas how to fix this?

**Comment by rschrenk** [comment] 2022-03-22 07:31
I think this is a duplicate of #5

**Closed by rschrenk** 2022-03-22 07:31 UTC
